### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by chuegel** [CactusSoft/zabbkit-ios#1]
Got the latest app from the AppStore. After connecting to the server and tap on *Data* I get `Expected status code in (200-299), got 500`

**Comment by yan-oreshchenkov** [comment]
So it just mean that server response with a kind of error (HTTP 500 - ServerError). I could not answer more exact. It could be anything starting from server-side issues to  unsupported Zabbix version. Try to check your server logs for details.

**Comment by chuegel** [comment]
closing for now
